In [33]:
#Questions 1:
#Create a numpy array starting from 2 till 50 with a stepsize of 3
import numpy as np
arr = np.arange(2, 50, 3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [20]:
#Questions 2
#Accept two lists of 5 elements each from the user.
#Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it

input_string = input("Enter a list1 elements separated by space ")

print("\n")
userList1 = input_string.split()
print("user list 1 ", userList1)
      
input_string = input("Enter a list2 elements separated by space ")
userList2 = input_string.split()
print("user list 2 ", userList2)
# converting list to array
import numpy as np
arr = np.append(userList1,userList2)
# displaying list
print ("List:", userList1,userList2) 
# displaying array
print ("Array: ", arr)

Enter a list1 elements separated by space 2 4 6 8 10


user list 1  ['2', '4', '6', '8', '10']
Enter a list2 elements separated by space 20 30 40 50 60
user list 2  ['20', '30', '40', '50', '60']
List: ['2', '4', '6', '8', '10'] ['20', '30', '40', '50', '60']
Array:  ['2' '4' '6' '8' '10' '20' '30' '40' '50' '60']


In [25]:
#Questions 3
# Write a code snippet to find the dimensions of a ndarray
import numpy as np 
  
# making a 3x3 array 
Nd = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]]) 
  
# before transpose 
print(Nd, end ='\n\n') 
  
# after transpose 
print(Nd.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [28]:
#Questions 4
# How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
# Hint: np.newaxis, np.expand_dims
a = np.array([1, 2, 3, 4, 5, 6])
a.shape
a1 = a[np.newaxis, :]
a1.shape
(1, 6)
b = np.expand_dims(a, axis=1)
b.shape
(6, 1)

(6, 1)

In [30]:
# Questions 5:
# Consider two square numpy arrays. Stack them vertically and horizontally.
# #Hint: Use vstack(), hstack()

## Vertical Stack
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

print('Vertical Append:', np.vstack((a, b)))
import numpy as np
c = np.array([1,2,3])
d = np.array([4,5,6])

print('Horizontal Append:', np.hstack((c, d)))

Vertical Append: [[1 2 3]
 [4 5 6]]
Horizontal Append: [1 2 3 4 5 6]


In [32]:
# Questions 6:
# How to get unique items and counts of unique items?
import numpy as np
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Total Count of unique items in the said array:")
print(np.asarray((unique_elements, counts_elements)))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Total Count of unique items in the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
